# Site settings
locale                   : "en-US"
site_theme               : "default"
title                    : "William Weller"
title_separator          : "-"
name                     : &name "William Weller"
description              : &description "Electronic and Electrical Engineer — portfolio, projects, and CV."
url                      : https://m0xwi.github.io
baseurl                  : ""
repository               : "m0xwi/m0xwi.github.io"

# Sidebar author profile
author:
  avatar           : "profile.jpg"
  name             : "William Weller"
  bio              : "Electronic and Electrical Engineer"
  location         : "Leeds"
  employer         : "University of Leeds"
  uri              :
  email            : "m0xwi@proton.me"
  github           : "m0xwi"
  linkedin         : "william-weller-2969a6163"

# Site behaviour
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               :
atom_feed:
  hide                   : true

# SEO
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics
analytics:
  provider               : "false"
  google:
    tracking_id          :

# Reading files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# HTML compression
compress_html:
  clippings: all
  ignore:
    envs: development
